services:
  - type: web
    name: visitor-intel-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TOKEN
        sync: false
      - key: IPINFO_TOKEN
        sync: false